// ── Static Student List ────────────────────────────────────────────────────
// Source: seed_users.py (73 students)
// Do NOT edit manually — keep in sync with seed_users.py

export const STUDENTS = [
  { rollNo: '24CS071', name: 'HARI VIGNESH' },
  { rollNo: '24CS072', name: 'HARINATH S' },
  { rollNo: '24CS073', name: 'HARINI C' },
  { rollNo: '24CS074', name: 'HARINI C H' },
  { rollNo: '24CS075', name: 'HARINI K' },
  { rollNo: '24CS076', name: 'HARIPRASATH M' },
  { rollNo: '24CS077', name: 'HARIPRIYAN A' },
  { rollNo: '24CS078', name: 'HARIS BALAJEE P L' },
  { rollNo: '24CS079', name: 'HARISH G' },
  { rollNo: '24CS080', name: 'HARISH KUMAR V' },
  { rollNo: '24CS081', name: 'HARISH S' },
  { rollNo: '24CS082', name: 'HARITHA E' },
  { rollNo: '24CS083', name: 'HARSHAD R' },
  { rollNo: '24CS084', name: 'HARSHINI A' },
  { rollNo: '24CS085', name: 'HARSHITHA M P' },
  { rollNo: '24CS086', name: 'HERANYAA T P' },
  { rollNo: '24CS087', name: 'ILAMSARAVANBALAJI PA' },
  { rollNo: '24CS088', name: 'JAGATHRATCHAGAN M' },
  { rollNo: '24CS089', name: 'JAIANISH J' },
  { rollNo: '24CS090', name: 'JAISURYA S' },
  { rollNo: '24CS091', name: 'JASHWANTH J' },
  { rollNo: '24CS092', name: 'JAY PRAKASH SAH' },
  { rollNo: '24CS093', name: 'JAYASURIYA S' },
  { rollNo: '24CS094', name: 'JAYATHEERTHAN P' },
  { rollNo: '24CS095', name: 'JEFF JEROME JABEZ' },
  { rollNo: '24CS096', name: 'JENITHA M' },
  { rollNo: '24CS097', name: 'JOSHUA RUBERT R' },
  { rollNo: '24CS098', name: 'JUMAANAH BASHEETH' },
  { rollNo: '24CS101', name: 'KANHAIYA PATEL' },
  { rollNo: '24CS102', name: 'KANISH KRISHNA J P' },
  { rollNo: '24CS103', name: 'KANISH M R' },
  { rollNo: '24CS104', name: 'KANISHKA S' },
  { rollNo: '24CS105', name: 'KANWAL KISHORE' },
  { rollNo: '24CS106', name: 'KARTHIKA A' },
  { rollNo: '24CS107', name: 'KARUNESH A R' },
  { rollNo: '24CS108', name: 'KATHIRAVAN S P' },
  { rollNo: '24CS109', name: 'KATHIRVEL S' },
  { rollNo: '24CS110', name: 'KAVIN KUMAR C' },
  { rollNo: '24CS111', name: 'KAVIN PRAKASH T' },
  { rollNo: '24CS112', name: 'KAVIPRIYA P' },
  { rollNo: '24CS113', name: 'KAVYA K' },
  { rollNo: '24CS114', name: 'KAVYASRI D' },
  { rollNo: '24CS115', name: 'KEERTHI AANAND K S' },
  { rollNo: '24CS116', name: 'KHAVIYA SREE M' },
  { rollNo: '24CS117', name: 'KIRITH MALINI D S' },
  { rollNo: '24CS118', name: 'KIRITHIKA S K' },
  { rollNo: '24CS119', name: 'KOWSALYA V' },
  { rollNo: '24CS120', name: 'KRISHNA VARUN K' },
  { rollNo: '24CS121', name: 'KRISHNAN A' },
  { rollNo: '24CS122', name: 'LAVANYA R' },
  { rollNo: '24CS123', name: 'LOGAPRABHU S' },
  { rollNo: '24CS124', name: 'LOGAVARSHHNI S' },
  { rollNo: '24CS125', name: 'MADHANIKA M' },
  { rollNo: '24CS126', name: 'MADHUMITHA Y' },
  { rollNo: '24CS127', name: 'MADHUSREE M' },
  { rollNo: '24CS128', name: 'MANASA DEVI CHAPAGAIN' },
  { rollNo: '24CS129', name: 'MANISH BASNET' },
  { rollNo: '24CS130', name: 'MANISH PRAKKASH M S' },
  { rollNo: '24CS131', name: 'MANOJ V' },
  { rollNo: '24CS132', name: 'MANOJKUMAR S' },
  { rollNo: '24CS133', name: 'MANSUR ANSARI' },
  { rollNo: '24CS134', name: 'MATHIYAZHINI S' },
  { rollNo: '24CS135', name: 'MATHUMITHA S' },
  { rollNo: '24CS136', name: 'MEKALA S' },
  { rollNo: '24CS137', name: 'MITHRHA Y' },
  { rollNo: '24CS138', name: 'MOHAMED ASIF S' },
  { rollNo: '24CS139', name: 'MOHAMMED SUHAIL M' },
  { rollNo: '24CS140', name: 'MOHAN KAARTHICK C' },
  { rollNo: 'LE01',   name: 'NAVEEN N' },
  { rollNo: 'LE02',   name: 'SUJAY S' },
  { rollNo: 'LE03',   name: 'ABDHUL KAREEM L' },
]

export const TOTAL = STUDENTS.length  // 73
